gameshop/gameshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('allauth.urls')),
    path('', home_view, name='home'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gameshop/products/urls.py
from django.urls import path
from .views import ProductsView, ProductDetail, CategoryDetail, DiscountProduct, SearchView, add_remove_cart, \
    add_remove_favorite

app_name = 'products'

urlpatterns = [
    path('catalog', ProductsView.as_view(), name='catalog'),
    path('category/<slug:category_slug>', CategoryDetail.as_view(), name='category'),
    path('discount/', DiscountProduct.as_view(), name='discount'),
    path('search/', SearchView.as_view(), name='search'),
    path('product/<slug:product_slug>', ProductDetail.as_view(), name='game'),
    path('product/add-favorite/<slug:product_slug>', add_remove_favorite, name='add-remove-favorite'),
    path('product/add-cart/<slug:product_slug>', add_remove_cart, name='add-remove-cart')
]

gameshop/profiles/urls.py
from django.urls import path
from .views import ProfileDetail, ShoppingCart, Favorite, CancelView, SuccessView, CreateCheckoutSessionView, \
    stripe_webhook, edit_profile_view

app_name = 'profiles'

urlpatterns = [
    path('shopping_cart/', ShoppingCart.as_view(), name='shopping-cart'),
    path('favorite/', Favorite.as_view(), name='favorite'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
    # path('create-payment-intent/<pk>/', StripeIntentView.as_view(), name='create-payment-intent'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path(f'success/', SuccessView.as_view(), name='success'),
    # path('success/', SuccessView.as_view(), name='success'),
    # path('', ProductLandingPageView.as_view(), name='landing-page'),
    path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('edit', edit_profile_view, name='edit-profile'),
    path('<slug:profile_slug>', ProfileDetail.as_view(), name='myprofile')
]

gameshop/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from phonenumber_field.modelfields import PhoneNumberField
import uuid


def get_random_code():
    code = str(uuid.uuid4())[:8].replace('-', '').lower()
    return code


class Profile(models.Model):
    first_name = models.CharField(max_length=100, blank=True, verbose_name='Имя')
    last_name = models.CharField(max_length=100, blank=True, verbose_name='Фамилия')
    number = PhoneNumberField(blank=True)
    country = models.CharField(max_length=100, blank=True)
    avatar = models.ImageField(default='avatars/avatar.png', upload_to='avatars', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='аватар')
    balance = models.DecimalField(max_digits=11, decimal_places=2, blank=True, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, db_index=True, verbose_name='URL')
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    objects = models.Manager()

    def get_absolute_url(self):
        return reverse('profiles', kwargs={'profile_slug': self.slug})

    def __str__(self):
        return str(self.user.username)


    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == "":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

gameshop/profiles/forms.py
from django import forms
from .models import Profile


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'number', 'country', 'avatar')

gameshop/profiles/views.py
import decimal
import os
import stripe as stripe
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormMixin, UpdateView, FormView

from .forms import EditProfileForm
from .models import Profile, User
from products.models import Product


stripe.api_key = settings.STRIPE_SECRET_KEY


class ShoppingCart(ListView):
    model = Product
    template_name = 'profiles/shopping_cart.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        products = Product.objects.filter(shopping_cart=self.request.user.profile)
        context = super().get_context_data(**kwargs)
        context['title'] = 'Корзина'
        context['products'] = products
        total_price = 0
        for product in products:
            total_price += product.get_final_price
        context['total_price'] = total_price

        return context


class SuccessView(TemplateView):
    template_name = "profiles/success.html"


class CancelView(TemplateView):
    template_name = "profiles/cancel.html"


class CreateCheckoutSessionView(View):
    def post(self, request, *args, **kwargs):
        products = Product.objects.filter(shopping_cart=self.request.user.profile)
        total_price = 0
        for product in products:
            total_price += product.get_final_price
        YOUR_DOMAIN = "http://127.0.0.1:8000/profiles/"
        line_items = []
        metadata = {}
        metadata['total_price'] = total_price
        metadata['slug'] = self.request.user.profile.slug
        for product in products:
            metadata[product.title] = 'product.url'
            line_items.append({
                    'price_data': {
                        'currency': 'rub',
                        'unit_amount': int(product.get_final_price) * 100,
                        'product_data': {
                            'name': product.title,
                        },
                    },
                    'quantity': 1,
                })
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=line_items,
            metadata=metadata,
            mode='payment',
            success_url=YOUR_DOMAIN + 'success/',
            cancel_url=YOUR_DOMAIN + 'cancel/',
        )

        return redirect(checkout_session.url, code=303)


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

        # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = stripe.checkout.Session.retrieve(
            event['data']['object']['id'],
            expand=['line_items'],
        )
        customer_email = session["customer_details"]["email"]
        message = ""
        for key, value in session["metadata"].items():
            message += f"\nНазвание товара: {key}, ссылка для скачивания: {value}"
        send_mail(
            subject="Вот Ваш продукт",
            message=f"Спасибо за покупку! Вот ваши товары:{message}",
            recipient_list=[customer_email],
            from_email='sanek_mamontov@mail.ru'
        )

        profile = Profile.objects.get(slug=session["metadata"]['slug'])
        products = Product.objects.filter(shopping_cart=profile)
        for product in products:
            product.shopping_cart.remove(profile)
            product.favorite.remove(profile)

        total_price = 0
        for product in products:
            total_price += product.get_final_price
        profile.balance = profile.balance - decimal.Decimal(session["metadata"]['total_price'])
        profile.save()

    return HttpResponse(status=200)


class Favorite(ListView):
    model = Product
    template_name = 'profiles/favorite.html'
    context_object_name = 'products'

    def get_queryset(self):
        qs = Product.objects.filter(favorite=self.request.user.profile)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Избранное'
        return context


class ProfileDetail(DetailView):
    model = Profile
    template_name = 'profiles/myprofile.html'
    context_object_name = 'profile'
    slug_url_kwarg = 'profile_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Личный кабинет'
        user = User.objects.get(username=self.request.user)
        profile = Profile.objects.get(user=user)
        context['profile'] = profile
        return context


def edit_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = EditProfileForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
            return render(request, 'profiles/myprofile.html', context)

    return render(request, 'profiles/edit_profile.html', context)

gameshop/profiles/templates/profiles/cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cancel</title>
</head>
<body>
Cancel!
</body>
</html>

gameshop/profiles/templates/profiles/edit_profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="row justify-content-start" style="margin-top:20px; margin-left:20px">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Редактировать" class="btn btn-success" name="edit_frm">
        </form>
    </div>
{% endblock content %}

gameshop/profiles/templates/profiles/favorite.html
{% extends 'base.html' %}
{% block content %}
    <div class="row justify-content-start" style="margin-top:20px; margin-left:20px">
            <ul class="list-unstyled">
                 {% for product in products %}
                    <li>
                        <h1>{{ product }}</h1>
                    </li>
                    {% if product.discount %}
                    <li>
                        <h5>Скидка {{ product.discount }}% Цена <del>{{ product.price }}</del> {{ product.get_final_price}}</h5>
                    </li>
                    {% else %}
                    <li>
                        <h5>Цена {{ product.get_final_price}}</h5>
                    </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'products:game' product.slug %}"><img style="max-width:17%" src={{product.image.url}}  class="img-fluid scale rounded-3"></a>
                    </li>
                    <br>
                    <li>
                        <a href="{% url 'products:add-remove-favorite' product.slug %}"><button class="btn btn-outline-success" type="submit">Удалить из желаемого</button></a>
                    </li>
                    <br>
                 {% endfor %}
            </ul>
        {% if not products %}
            <h3>У вас нет игр в избранном</h3>
            <a href="{% url 'products:catalog' %}"><button class="btn btn-outline-success" type="submit">К покупкам!</button></a>
        {% endif %}
    </div>
{% endblock content %}

gameshop/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}
{% block content %}
    <div class="row justify-content-start" style="margin-top:20px; margin-left:20px">
        <ul class="list-unstyled">
            <li>
                <h5>{{ profile.first_name }} {{ profile.last_name }}</h5>
            </li>
            <li>
                <h5>Телефон {{ profile.number }}</h5>
            </li>
            <li>
                <h5>Страна {{ profile.country }}</h5>
            </li>
            <li>
                <h5>Баланс {{ profile.balance }}</h5>
            </li>
            <li>
                <img src={{profile.avatar.url}} style="max-width:14%" class="img-fluid">
            </li>
        </ul>
    </div>
{% endblock content %}

gameshop/profiles/templates/profiles/shopping_cart.html
{% extends 'base.html' %}
{% block content %}
<!--    <link rel="stylesheet" href="style.css">-->
    <script src="https://js.stripe.com/v3/"></script>
    <div class="row justify-content-start" style="margin-top:20px; margin-left:20px;padding-bottom:20px">
            <ul class="list-unstyled">
                 {% for product in products %}
                    <li>
                        <h1>{{ product }}</h1>
                    </li>
                    {% if product.discount %}
                    <li>
                        <h5>Скидка {{ product.discount }}% Цена <del>{{ product.price }}</del> {{ product.get_final_price}}</h5>
                    </li>
                    {% else %}
                    <li>
                        <h5>Цена {{ product.get_final_price}}</h5>
                    </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'products:game' product.slug %}"><img style="max-width:17%" src={{product.image.url}}  class="img-fluid scale rounded-3"></a>
                    </li>
                    <br>
                    <li>
                        <a href="{% url 'products:add-remove-cart' product.slug %}"><button class="btn btn-outline-success" type="submit">Удалить из корзины</button></a>
                    </li>
                    <br>
                 {% endfor %}
            </ul>
        {% if total_price %}
            <h3>Итоговая цена {{ total_price }}</h3>
            <form action="{% url 'profiles:create-checkout-session' %}" method="POST">
                {% csrf_token %}
                <button type="submit" id="checkout-button" class="btn btn-success">К оплате</button>
                <br>
            </form>
        {% else %}
            <h3>У вас нет игр в корзине</h3>
            <a href="{% url 'products:catalog' %}"><button class="btn btn-outline-success" type="submit">К покупкам!</button></a>
        {% endif %}

    </div>
{% endblock content %}

gameshop/profiles/templates/profiles/success.html
{% extends 'base.html' %}
<title>Success</title>
{% block content %}
    <h1>Поздравляем с покупкой!</h1>
{% endblock content %}