gameshop/gameshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('allauth.urls')),
    path('', home_view, name='home'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gameshop/products/urls.py
from django.urls import path
from .views import ProductsView, ProductDetail, CategoryDetail, DiscountProduct, SearchView, add_remove_cart, \
    add_remove_favorite

app_name = 'products'

urlpatterns = [
    path('catalog', ProductsView.as_view(), name='catalog'),
    path('category/<slug:category_slug>', CategoryDetail.as_view(), name='category'),
    path('discount/', DiscountProduct.as_view(), name='discount'),
    path('search/', SearchView.as_view(), name='search'),
    path('product/<slug:product_slug>', ProductDetail.as_view(), name='game'),
    path('product/add-favorite/<slug:product_slug>', add_remove_favorite, name='add-remove-favorite'),
    path('product/add-cart/<slug:product_slug>', add_remove_cart, name='add-remove-cart')
]

gameshop/profiles/urls.py
from django.urls import path
from .views import ProfileDetail, ShoppingCart, Favorite, CancelView, SuccessView, CreateCheckoutSessionView, \
    stripe_webhook, edit_profile_view

app_name = 'profiles'

urlpatterns = [
    path('shopping_cart/', ShoppingCart.as_view(), name='shopping-cart'),
    path('favorite/', Favorite.as_view(), name='favorite'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
    # path('create-payment-intent/<pk>/', StripeIntentView.as_view(), name='create-payment-intent'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path(f'success/', SuccessView.as_view(), name='success'),
    # path('success/', SuccessView.as_view(), name='success'),
    # path('', ProductLandingPageView.as_view(), name='landing-page'),
    path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('edit', edit_profile_view, name='edit-profile'),
    path('<slug:profile_slug>', ProfileDetail.as_view(), name='myprofile')
]

gameshop/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/4497e0da56.js" crossorigin="anonymous"></script>
    <title>{{title}}</title>
  </head>
  <body>
    <div class="container-fluid">
      <h1 style="margin-top:15px; margin-left:20px">GameShop</h1>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
      {% include 'navbar.html' %}
      {% block content %}
      {% endblock content %}
    </div>
  </body>
  <style>
    .scale {
     transition: 1s
    }
    .scale:hover {
     transform: scale(1.03)
    }
   </style>
</html>

gameshop/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% endblock content %}

gameshop/templates/navbar.html
{% url 'products:catalog' as catalog %}
{% url 'profiles:myprofile' request.user.profile.slug as myprofile %}
{% url 'home' as home %}
{% url 'products:discount' as discount %}
{% url 'profiles:shopping-cart' as shopping_cart %}
<body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{{ home }}">На главную</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ catalog }}">Каталог</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ discount }}">Товары по скидкам</a>
                </li>
                {% if categories %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Категории
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for category in categories %}
                                <a class="dropdown-item" href="{% url 'products:category' category.slug%}">{{ category }}</a>
                            {% endfor %}
                        </div>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <form action="{% url 'products:search' %}" method="GET" class="d-flex" role="search">
                      <input name="search" class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </li>
            </ul>

            <ul class="navbar-nav ">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" style="color:green; font-weight: bold">
                    <i class="fa-solid fa-coins"></i>
                     {{ request.user.profile.balance }} ₽
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ myprofile }}">Мой кабинет <i class="fa-regular fa-user"></i></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ shopping_cart }}">Корзина <i class="fa-solid fa-cart-shopping"></i></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'profiles:favorite' %}">Желаемое <i class="fa-regular fa-heart"></i></a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">Выход</a>
                </li>
              {% else %}
                  <a class="nav-link" href="{% url 'account_login' %}">&nbsp Вход</a>
              {% endif %}
              </ul>
        </div>
    </div>
</nav>